# -*- mode: python ; coding: utf-8 -*-

block_cipher = None

a = Analysis(
    ['src/main_gui.py'],
    pathex=[],
    binaries=[
        ('libmediainfo.0.dylib', '.'),
        ('Mandarin.dat', '.'),
    ],
    datas=[
        ('static', 'static'),
        ('docs/requirements.txt', 'docs'),
        ('media', 'media'),
        ('temp', 'temp'),
        ('Mandarin.dat', 'xpinyin'),
        ('LICENSE', '.'),
        ('README.md', '.'),
        ('readme.txt', '.'),
        ('.env.example', '.env.example'),
    ],
    hiddenimports=[
        'PyQt6',
        'PyQt6.QtCore',
        'PyQt6.QtGui',
        'PyQt6.QtWidgets',
        'flask',
        'flask_cors',
        'requests',
        'PIL',
        'cv2',
        'numpy',
        'pymediainfo',
        'torf',
        'pyperclip',
        'xpinyin',
        'click',
        'colorama',
        'dotenv',
        'jinja2',
        'werkzeug',
        'prompt_toolkit',
        'src.gui.ui.mainwindow',
        'src.gui.ui.settings',
        'src.gui.ui.toast',
        'src.core.autofeed',
        'src.core.mediainfo',
        'src.core.picturebed',
        'src.core.poster',
        'src.core.ptgen',
        'src.core.rename',
        'src.core.screenshot',
        'src.core.tool',
        'src.api.startapi',
        'src.config.settings',
        'src.utils.logger',
        'src.utils.file_utils',
        'src.utils.exceptions',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[
        'PyQt5',
        'PyQt5.QtCore',
        'PyQt5.QtGui',
        'PyQt5.QtWidgets',
        'PySide2',
        'PySide6',
        'shiboken2',
        'shiboken6',
    ],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name='Publish Helper',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon='static/ph-bjd.ico',
)
